function env(key: keyof ImportMetaEnv, fallback = ""): string {
  const viteValue = import.meta.env[key];
  if (viteValue !== undefined && viteValue !== "") {
    return viteValue;
  }
  if (typeof process !== "undefined" && process.env[key]) {
    return process.env[key]!;
  }
  return fallback;
}

export const AIRTABLE_BASE_ID = env("VITE_AIRTABLE_BASE_ID");
export const AIRTABLE_API_KEY = env("VITE_AIRTABLE_API_KEY");

export const AIRTABLE_TABLE_NAME = env("VITE_AIRTABLE_TABLE_NAME", "Users");
export const AIRTABLE_EMAIL_FIELD = env("VITE_AIRTABLE_EMAIL_FIELD", "email");
export const AIRTABLE_PASSWORD_FIELD = env("VITE_AIRTABLE_PASSWORD_FIELD", "Password");
export const AIRTABLE_SHOW_HABITS_FIELD = env("VITE_AIRTABLE_SHOW_HABITS_FIELD", "show_habits");
export const AIRTABLE_SHOW_MEASURES_FIELD = env("VITE_AIRTABLE_SHOW_MEASURES_FIELD", "show_measures");

export const AIRTABLE_HABITS_TABLE_NAME = env("VITE_AIRTABLE_HABITS_TABLE_NAME", "Habits");
export const AIRTABLE_HABITS_USER_ID_FIELD = env("VITE_AIRTABLE_HABITS_USER_ID_FIELD", "user_id");
export const AIRTABLE_HABITS_NAME_FIELD = env("VITE_AIRTABLE_HABITS_NAME_FIELD", "name");
export const AIRTABLE_HABITS_FREQUENCY_FIELD = env("VITE_AIRTABLE_HABITS_FREQUENCY_FIELD", "frequency");
export const AIRTABLE_HABITS_CREATED_AT_FIELD = env("VITE_AIRTABLE_HABITS_CREATED_AT_FIELD", "created_at");

export const AIRTABLE_HABITS_LOGS_TABLE_NAME = env("VITE_AIRTABLE_HABITS_LOGS_TABLE_NAME", "HabitsLogs");
export const AIRTABLE_HABITS_LOGS_HABIT_ID_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_HABIT_ID_FIELD", "habit_id");
export const AIRTABLE_HABITS_LOGS_USER_ID_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_USER_ID_FIELD", "user_id");
export const AIRTABLE_HABITS_LOGS_COMPLETED_AT_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_COMPLETED_AT_FIELD", "completed_at");
export const AIRTABLE_HABITS_LOGS_FREQUENCY_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_FREQUENCY_FIELD", "frequency");
export const AIRTABLE_HABITS_LOGS_PERIOD_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_PERIOD_FIELD", "period");

export const AIRTABLE_MEASURES_TABLE_NAME = env("VITE_AIRTABLE_MEASURES_TABLE_NAME", "Measures");
export const AIRTABLE_MEASURES_MEASURE_ID_FIELD = env("VITE_AIRTABLE_MEASURES_MEASURE_ID_FIELD", "measure_id");
export const AIRTABLE_MEASURES_USER_ID_FIELD = env("VITE_AIRTABLE_MEASURES_USER_ID_FIELD", "user_id");
export const AIRTABLE_MEASURES_DATE_FIELD = env("VITE_AIRTABLE_MEASURES_DATE_FIELD", "date");
export const AIRTABLE_MEASURES_WEIGHT_FIELD = env("VITE_AIRTABLE_MEASURES_WEIGHT_FIELD", "weight");
export const AIRTABLE_MEASURES_ARM_FIELD = env("VITE_AIRTABLE_MEASURES_ARM_FIELD", "arm");
export const AIRTABLE_MEASURES_BUST_FIELD = env("VITE_AIRTABLE_MEASURES_BUST_FIELD", "bust");
export const AIRTABLE_MEASURES_WAIST_FIELD = env("VITE_AIRTABLE_MEASURES_WAIST_FIELD", "waist");
export const AIRTABLE_MEASURES_HIP_FIELD = env("VITE_AIRTABLE_MEASURES_HIP_FIELD", "hip");
export const AIRTABLE_MEASURES_THIGH_FIELD = env("VITE_AIRTABLE_MEASURES_THIGH_FIELD", "thigh");

export const AIRTABLE_NOTES_TABLE_NAME = env("VITE_AIRTABLE_NOTES_TABLE_NAME", "Notes");
export const AIRTABLE_NOTES_ID_FIELD = env("VITE_AIRTABLE_NOTES_ID_FIELD", "id");
export const AIRTABLE_NOTES_CONTENT_FIELD = env("VITE_AIRTABLE_NOTES_CONTENT_FIELD", "Notes");
export const AIRTABLE_NOTES_ASSIGNEES_FIELD = env("VITE_AIRTABLE_NOTES_ASSIGNEES_FIELD", "Assignees");
export const AIRTABLE_NOTES_STATUS_FIELD = env("VITE_AIRTABLE_NOTES_STATUS_FIELD", "Status");
export const AIRTABLE_NOTES_ATTACHMENTS_FIELD = env("VITE_AIRTABLE_NOTES_ATTACHMENTS_FIELD", "Attachments");
export const AIRTABLE_NOTES_TAGS_FIELD = env("VITE_AIRTABLE_NOTES_TAGS_FIELD", "tags");
export const AIRTABLE_NOTES_CREATED_AT_FIELD = env("VITE_AIRTABLE_NOTES_CREATED_AT_FIELD", "created_at");
